version: '3'
# External port: 24774 ('chrpg')
services:
  postgres:
    image: postgres:9.6.5-alpine
    ports:
      - 24774:5432
    restart: unless-stopped
    environment:
      POSTGRES_DB: chr-dev
      POSTGRES_USER: chr-dev
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
